
function PCal_NoiseBurst_HighLowStatsITPC_ANOVA(homedir,low,high)

cd(homedir)

DataTlow = readtable(['VMPandPMP_NoiseBurst_' low '_ITPCmean.csv']);
DataThigh = readtable(['VMPandPMP_NoiseBurst_' high '_ITPCmean.csv']);

% we're going to do this on the non-normalized data, so no need to break up
% the table, just to stack

y = vertcat(DataThigh.Theta_mean, DataThigh.Alpha_mean,...
    DataThigh.Beta_mean, DataThigh.GammaLow_mean, DataThigh.GammaHigh_mean,...
    DataTlow.Theta_mean, DataTlow.Alpha_mean,...
    DataTlow.Beta_mean, DataTlow.GammaLow_mean, DataTlow.GammaHigh_mean);

Group = vertcat(DataThigh.Group, DataThigh.Group,...
    DataThigh.Group, DataThigh.Group, DataThigh.Group,...
    DataTlow.Group, DataTlow.Group,...
    DataTlow.Group, DataTlow.Group, DataTlow.Group);

Condition = vertcat(repmat("high",70,1), repmat("high",70,1),...
    repmat("high",70,1), repmat("high",70,1), repmat("high",70,1),...
    repmat("low",70,1), repmat("low",70,1),...
    repmat("low",70,1), repmat("low",70,1), repmat("low",70,1));

Layer = vertcat(DataThigh.Layer, DataThigh.Layer,...
    DataThigh.Layer, DataThigh.Layer, DataThigh.Layer,...
    DataTlow.Layer, DataTlow.Layer,...
    DataTlow.Layer, DataTlow.Layer, DataTlow.Layer);

Freq = vertcat(repmat("theta",70,1), repmat("alpha",70,1),...
    repmat("beta",70,1), repmat("low gam",70,1), repmat("high gam",70,1),...
    repmat("theta",70,1), repmat("alpha",70,1),...
    repmat("beta",70,1), repmat("low gam",70,1), repmat("high gam",70,1));




% Set up anova. Factors: group, layer, click-freq
[p, tbl] = anovan(y,{Group Condition Layer Freq},'model','interaction','varnames',{'Group','Condition','Layer','Freq'});

save('ANOVA_NB_HighLow_ITPC.mat','p')